// GENERATED by scripts/gen_codes.py from core/schema/codes.v1.json and events.v1.json -- do not edit.
// SPDX-License-Identifier: AGPL-3.0-or-later
// swiftlint:disable all
import Foundation

public let engineProtocolVersion = 1

public enum CodeKind: String, Codable, Sendable { case error, warning, note, result }
public enum DeviceModifiedDefault: String, Codable, Sendable { case no, yes, unknown, dynamic }

/// App actions offered for a code (labels: action.<id>).
public enum CodeAction: String, CaseIterable, Codable, Sendable {
    case autoNewBackup = "auto_new_backup"
    case back
    case backS03 = "back_s03"
    case backS05 = "back_s05"
    case backS07 = "back_s07"
    case chooseLocation = "choose_location"
    case `continue`
    case continueS16 = "continue_s16"
    case diagReport = "diag_report"
    case help
    case newBackup = "new_backup"
    case `none`
    case prepareAndroid = "prepare_android"
    case quit
    case recheck
    case reenterPassword = "reenter_password"
    case resetThreema = "reset_threema"
    case retry
    case seeVersions = "see_versions"
    case setEncryption = "set_encryption"
}

/// Every engine code of protocol v1. Unknown codes from a newer engine map to F-INTERNAL (DESIGN §5.7).
public enum EngineCode: String, CaseIterable, Codable, Sendable {
    case E_ANDROID_FORMAT_NEW
    case E_ANDROID_FORMAT_UNVERIFIED
    case E_ANDROID_INCOMPLETE
    case E_ANDROID_NO_TEXT
    case E_ANDROID_PASSWORD
    case E_BACKUP_ENCRYPTION_OFF
    case E_BACKUP_FAILED
    case E_BACKUP_PASSWORD
    case E_CANCELLED
    case E_DEV_BATTERY
    case E_DEV_DISCONNECTED
    case E_DEV_LOCKED
    case E_DEV_MANAGED
    case E_DEV_MULTIPLE
    case E_DEV_NONE
    case E_DEV_OTHER
    case E_DEV_UNTRUSTED
    case E_GUARD_AIRPLANE
    case E_GUARD_DCIM_CHANGED
    case E_GUARD_FINDMY
    case E_GUARD_FRESHNESS
    case E_GUARD_IPHONE_SPACE
    case E_GUARD_PHOTOS_LIMIT
    case E_GUARD_ROLLBACK_NOT_ALLOWED
    case E_GUARD_ROLLBACK_WINDOW
    case E_GUARD_SET_INTEGRITY
    case E_HOST_ARCH
    case E_HOST_FS_NOT_APFS
    case E_HOST_MACOS_OLD
    case E_HOST_POWER
    case E_HOST_SPACE
    case E_IMPORT_DUPLICATE_CHAT
    case E_INTERNAL
    case E_IOS_BLOCKED
    case E_IOS_CHANGED
    case E_IOS_UNKNOWN
    case E_NETWORK_BLOCKED
    case E_POST_TOO_EARLY
    case E_PROTOCOL
    case E_RESTORE_DEVICE_ERROR
    case E_RESTORE_INTERRUPTED
    case E_RESTORE_NOT_STARTED
    case E_SECRETS_MISSING
    case E_THREEMA_ID_MISMATCH
    case E_THREEMA_ID_UNREADABLE
    case E_THREEMA_MISSING
    case E_THREEMA_MODEL_UNKNOWN
    case E_THREEMA_NOT_SET_UP
    case E_THREEMA_RETENTION
    case E_THREEMA_VARIANT
    case N_APPLE_ACCOUNT_RERUN
    case N_APPLE_PAY_READD
    case N_CALENDAR_SYNC_TABLES
    case N_KEYCHAIN_ITEMS_ADDED
    case N_MAIL_LOCAL_MAY_BE_GONE
    case N_POSTER_CACHE_REGENERATED
    case N_SHORTCUTS_CATALOGUE_REGENERATED
    case R_OK
    case R_RESTORE_SENT_LINK_LOST
    case W_ANDROID_MEDIA_PARTIAL
    case W_BACKUP_RETRY
    case W_DEVICE_RETRY
    case W_FILEVAULT_OFF
    case W_LOW_HOST_SPACE_MARGIN
    case W_MISSING_KEY_SENDERS
    case W_OWN_UNSENT_AS_SENT
    case W_USB2_SLOW

    public struct Info: Sendable {
        public let kind: CodeKind
        public let screen: String
        public let exitCode: Int32
        public let deviceModified: DeviceModifiedDefault
        public let retryable: Bool
        public let needsNewBackup: Bool
        public let actions: [CodeAction]
        public let dataKeys: [String]
    }

    public var info: Info {
        switch self {
        case .E_ANDROID_FORMAT_NEW: return Info(kind: .error, screen: "F-ANDROID-FORMAT", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.seeVersions], dataKeys: ["ref", "format_version"])
        case .E_ANDROID_FORMAT_UNVERIFIED: return Info(kind: .error, screen: "F-ANDROID-FORMAT", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.seeVersions], dataKeys: ["ref", "format_version"])
        case .E_ANDROID_INCOMPLETE: return Info(kind: .error, screen: "S05", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.backS05], dataKeys: ["ref"])
        case .E_ANDROID_NO_TEXT: return Info(kind: .error, screen: "S05", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.backS05], dataKeys: ["ref"])
        case .E_ANDROID_PASSWORD: return Info(kind: .error, screen: "S05", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.reenterPassword], dataKeys: ["ref"])
        case .E_BACKUP_ENCRYPTION_OFF: return Info(kind: .error, screen: "S10a", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.setEncryption], dataKeys: [])
        case .E_BACKUP_FAILED: return Info(kind: .error, screen: "F-BACKUP-FAILED", exitCode: 3, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.retry], dataKeys: ["attempts"])
        case .E_BACKUP_PASSWORD: return Info(kind: .error, screen: "F-PW-WRONG", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.reenterPassword], dataKeys: ["attempt", "max"])
        case .E_CANCELLED: return Info(kind: .error, screen: "S00", exitCode: 4, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.back], dataKeys: [])
        case .E_DEV_BATTERY: return Info(kind: .error, screen: "F-DEV-BATTERY", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: ["battery_pct", "charging"])
        case .E_DEV_DISCONNECTED: return Info(kind: .error, screen: "F-DEV-DISCONNECTED", exitCode: 3, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: [])
        case .E_DEV_LOCKED: return Info(kind: .error, screen: "S03", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: [])
        case .E_DEV_MANAGED: return Info(kind: .error, screen: "F-DEV-MANAGED", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.quit], dataKeys: [])
        case .E_DEV_MULTIPLE: return Info(kind: .error, screen: "F-DEV-MULTI", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: ["count"])
        case .E_DEV_NONE: return Info(kind: .error, screen: "S03", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: [])
        case .E_DEV_OTHER: return Info(kind: .error, screen: "F-DEV-OTHER", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: [])
        case .E_DEV_UNTRUSTED: return Info(kind: .error, screen: "S03", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: [])
        case .E_GUARD_AIRPLANE: return Info(kind: .error, screen: "F-AIRPLANE", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.newBackup], dataKeys: [])
        case .E_GUARD_DCIM_CHANGED: return Info(kind: .error, screen: "F-DCIM", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.newBackup], dataKeys: ["files"])
        case .E_GUARD_FINDMY: return Info(kind: .error, screen: "F-FINDMY", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry], dataKeys: ["source"])
        case .E_GUARD_FRESHNESS: return Info(kind: .error, screen: "F-FRESHNESS", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.autoNewBackup], dataKeys: ["age_min", "limit_min"])
        case .E_GUARD_IPHONE_SPACE: return Info(kind: .error, screen: "F-IPHONE-SPACE", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.help], dataKeys: ["need_bytes", "free_bytes"])
        case .E_GUARD_PHOTOS_LIMIT: return Info(kind: .error, screen: "F-PHOTOS-LIMIT", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.help], dataKeys: ["limit_bytes", "photos_bytes"])
        case .E_GUARD_ROLLBACK_NOT_ALLOWED: return Info(kind: .error, screen: "S21", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["verdict"])
        case .E_GUARD_ROLLBACK_WINDOW: return Info(kind: .error, screen: "S21", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["age_min", "limit_min"])
        case .E_GUARD_SET_INTEGRITY: return Info(kind: .error, screen: "F-INTERNAL", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["sub"])
        case .E_HOST_ARCH: return Info(kind: .error, screen: "F-HOST-UNSUPPORTED", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.quit], dataKeys: ["macos", "arch"])
        case .E_HOST_FS_NOT_APFS: return Info(kind: .error, screen: "F-HOST-APFS", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.chooseLocation], dataKeys: ["fs"])
        case .E_HOST_MACOS_OLD: return Info(kind: .error, screen: "F-HOST-UNSUPPORTED", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.quit], dataKeys: ["macos", "arch"])
        case .E_HOST_POWER: return Info(kind: .error, screen: "F-HOST-POWER", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.recheck], dataKeys: ["power"])
        case .E_HOST_SPACE: return Info(kind: .error, screen: "F-HOST-SPACE", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.recheck, .chooseLocation], dataKeys: ["need_bytes", "free_bytes"])
        case .E_IMPORT_DUPLICATE_CHAT: return Info(kind: .error, screen: "F-IMPORT-DUP", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["chats"])
        case .E_INTERNAL: return Info(kind: .error, screen: "F-INTERNAL", exitCode: 2, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["sub", "exc", "where"])
        case .E_IOS_BLOCKED: return Info(kind: .error, screen: "F-IOS-UNKNOWN", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.prepareAndroid, .seeVersions], dataKeys: ["ios_version", "ios_build"])
        case .E_IOS_CHANGED: return Info(kind: .error, screen: "F-IOS-CHANGED", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: true, actions: [.backS03], dataKeys: ["ios_build"])
        case .E_IOS_UNKNOWN: return Info(kind: .error, screen: "F-IOS-UNKNOWN", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.prepareAndroid, .seeVersions], dataKeys: ["ios_version", "ios_build"])
        case .E_NETWORK_BLOCKED: return Info(kind: .error, screen: "F-INTERNAL", exitCode: 2, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["sub", "exc", "where"])
        case .E_POST_TOO_EARLY: return Info(kind: .error, screen: "S18", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.newBackup], dataKeys: [])
        case .E_PROTOCOL: return Info(kind: .error, screen: "F-INTERNAL", exitCode: 2, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["sub", "exc", "where"])
        case .E_RESTORE_DEVICE_ERROR: return Info(kind: .error, screen: "S16", exitCode: 3, deviceModified: .unknown, retryable: false, needsNewBackup: false, actions: [.continueS16], dataKeys: ["last_progress"])
        case .E_RESTORE_INTERRUPTED: return Info(kind: .error, screen: "F-RESTORE-MID", exitCode: 3, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry, .continueS16], dataKeys: ["last_progress"])
        case .E_RESTORE_NOT_STARTED: return Info(kind: .error, screen: "F-RESTORE-BEFORE", exitCode: 3, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.retry, .diagReport], dataKeys: ["reason"])
        case .E_SECRETS_MISSING: return Info(kind: .error, screen: "F-INTERNAL", exitCode: 2, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.diagReport], dataKeys: ["sub", "exc", "where"])
        case .E_THREEMA_ID_MISMATCH: return Info(kind: .error, screen: "F-THREEMA-ID", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [.backS05], dataKeys: [])
        case .E_THREEMA_ID_UNREADABLE: return Info(kind: .error, screen: "F-THREEMA-ID", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.diagReport, .newBackup], dataKeys: [])
        case .E_THREEMA_MISSING: return Info(kind: .error, screen: "F-THREEMA-MISSING", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.backS07], dataKeys: [])
        case .E_THREEMA_MODEL_UNKNOWN: return Info(kind: .error, screen: "F-THREEMA-VERSION", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.seeVersions], dataKeys: ["app_version"])
        case .E_THREEMA_NOT_SET_UP: return Info(kind: .error, screen: "F-THREEMA-SETUP", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.backS07], dataKeys: [])
        case .E_THREEMA_RETENTION: return Info(kind: .error, screen: "F-THREEMA-RETENTION", exitCode: 1, deviceModified: .no, retryable: true, needsNewBackup: true, actions: [.backS07], dataKeys: [])
        case .E_THREEMA_VARIANT: return Info(kind: .error, screen: "F-THREEMA-VARIANT", exitCode: 1, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [.quit], dataKeys: ["variant"])
        case .N_APPLE_ACCOUNT_RERUN: return Info(kind: .note, screen: "S19", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .N_APPLE_PAY_READD: return Info(kind: .note, screen: "S19", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .N_CALENDAR_SYNC_TABLES: return Info(kind: .note, screen: "S19", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .N_KEYCHAIN_ITEMS_ADDED: return Info(kind: .note, screen: "S19", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .N_MAIL_LOCAL_MAY_BE_GONE: return Info(kind: .note, screen: "S19", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .N_POSTER_CACHE_REGENERATED: return Info(kind: .note, screen: "S19", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .N_SHORTCUTS_CATALOGUE_REGENERATED: return Info(kind: .note, screen: "S19", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .R_OK: return Info(kind: .result, screen: "", exitCode: 0, deviceModified: .dynamic, retryable: false, needsNewBackup: false, actions: [.`continue`], dataKeys: [])
        case .R_RESTORE_SENT_LINK_LOST: return Info(kind: .result, screen: "S16", exitCode: 0, deviceModified: .yes, retryable: false, needsNewBackup: false, actions: [.continueS16], dataKeys: ["last_progress"])
        case .W_ANDROID_MEDIA_PARTIAL: return Info(kind: .warning, screen: "S06", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: ["media_present", "media_total"])
        case .W_BACKUP_RETRY: return Info(kind: .warning, screen: "S12", exitCode: 0, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [], dataKeys: ["attempt", "max"])
        case .W_DEVICE_RETRY: return Info(kind: .warning, screen: "S03", exitCode: 0, deviceModified: .no, retryable: true, needsNewBackup: false, actions: [], dataKeys: ["attempt", "max"])
        case .W_FILEVAULT_OFF: return Info(kind: .warning, screen: "S02", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        case .W_LOW_HOST_SPACE_MARGIN: return Info(kind: .warning, screen: "S02", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: ["need_bytes", "free_bytes"])
        case .W_MISSING_KEY_SENDERS: return Info(kind: .warning, screen: "S06", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: ["missing_key_groups", "missing_key_messages", "missing_key_senders"])
        case .W_OWN_UNSENT_AS_SENT: return Info(kind: .warning, screen: "S06", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: ["own_unsent_as_sent"])
        case .W_USB2_SLOW: return Info(kind: .warning, screen: "S12", exitCode: 0, deviceModified: .no, retryable: false, needsNewBackup: false, actions: [], dataKeys: [])
        }
    }

    public var titleKey: String { "code.\(rawValue).title" }
    public var bodyKey: String { "code.\(rawValue).body" }
    public var actionKey: String { "code.\(rawValue).action" }
}

/// tmcore commands (DESIGN §5.4).
public enum EngineCommand: String, CaseIterable, Codable, Sendable {
    case version
    case selftest
    case hostCheck = "host-check"
    case androidInspect = "android-inspect"
    case androidNormalize = "android-normalize"
    case deviceWatch = "device-watch"
    case deviceStatus = "device-status"
    case encryptionEnable = "encryption-enable"
    case backup
    case prepare
    case restore
    case postcheck
    case rollbackThreema = "rollback-threema"
    case sessionStatus = "session-status"
    case diagReport = "diag-report"
    case cleanup
}

/// Phase names; per command see phasesByCommand.
public enum EnginePhase: String, CaseIterable, Codable, Sendable {
    case backup
    case build
    case bundle
    case checks
    case collect
    case compare
    case confirmOnDevice = "confirm_on_device"
    case count
    case delete
    case extract
    case guards
    case `import`
    case imports
    case inspect
    case media
    case netguard
    case read
    case reboot
    case send
    case threema
    case verdict
    case verify
}

public let phasesByCommand: [EngineCommand: [EnginePhase]] = [
    .version: [],
    .sessionStatus: [],
    .deviceWatch: [],
    .selftest: [.imports, .bundle, .netguard],
    .hostCheck: [.checks],
    .androidInspect: [.inspect],
    .androidNormalize: [.read, .media, .verify],
    .deviceStatus: [.read],
    .encryptionEnable: [.confirmOnDevice],
    .backup: [.backup, .checks],
    .prepare: [.extract, .`import`, .count, .build, .verify],
    .restore: [.guards, .send, .reboot],
    .rollbackThreema: [.build, .guards, .send, .reboot],
    .postcheck: [.threema, .compare, .verdict],
    .diagReport: [.collect],
    .cleanup: [.delete],
]

/// Check ids of 'check' events.
public enum CheckID: String, CaseIterable, Codable, Sendable {
    case airplane
    case androidFile = "android_file"
    case androidFormat = "android_format"
    case androidMedia = "android_media"
    case androidPassword = "android_password"
    case androidText = "android_text"
    case arch
    case battery
    case buddyAnswer = "buddy_answer"
    case bundleHashes = "bundle_hashes"
    case compatIos = "compat_ios"
    case coredataOpen = "coredata_open"
    case dcimUnchanged = "dcim_unchanged"
    case device
    case duplicateChat = "duplicate_chat"
    case encryption
    case extract
    case filevault
    case findmy
    case freeSpace = "free_space"
    case freeze
    case freshness
    case fsApfs = "fs_apfs"
    case identity
    case `import`
    case iosUnchanged = "ios_unchanged"
    case iphoneSpace = "iphone_space"
    case keychainItems = "keychain_items"
    case macos
    case managed
    case modules
    case netguard
    case p2VerifyImport = "p2_verify_import"
    case p3Payload = "p3_payload"
    case p4Strict = "p4_strict"
    case password
    case photosLimit = "photos_limit"
    case postAfterRestore = "post_after_restore"
    case power
    case purplebuddy
    case restoreset
    case rollbackAllowed = "rollback_allowed"
    case rollbackWindow = "rollback_window"
    case setIntegrity = "set_integrity"
    case threemaAnswer = "threema_answer"
    case threemaModel = "threema_model"
    case threemaRetention = "threema_retention"
    case threemaSetup = "threema_setup"
    case threemaVariant = "threema_variant"
    case verifyImport = "verify_import"
    case verifyRestoreset = "verify_restoreset"
}

/// Postcheck verdicts in priority order (DESIGN §7).
public enum Verdict: String, CaseIterable, Codable, Sendable {
    case setupFull = "setup_full"
    case dataKeychain = "data_keychain"
    case data
    case threemaOnly = "threema_only"
    case restoreState = "restore_state"
    case needsAnswer = "needs_answer"
    case okWithNotes = "ok_with_notes"
    case ok
}

/// Event types.
public enum EventType: String, CaseIterable, Codable, Sendable {
    case hello
    case phase
    case progress
    case check
    case prompt
    case retry
    case device
    case critical
    case note
    case result
}

/// Prompt overlays.
public enum PromptKind: String, CaseIterable, Codable, Sendable {
    case unlockDevice = "unlock_device"
    case trustDevice = "trust_device"
    case passcodeOnDevice = "passcode_on_device"
    case keepCable = "keep_cable"
}

/// device-watch states.
public enum DeviceState: String, CaseIterable, Codable, Sendable {
    case `none`
    case locked
    case untrusted
    case ready
    case multiple
    case disconnected
}
