#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
gen_codes.py -- core/schema/codes.v1.json (+ events.v1.json enums) -> Swift + string catalog keys (DESIGN §5.5).

  python3 scripts/gen_codes.py            # write app/Sources/Engine/Codes.generated.swift and merge the
                                          # managed keys into app/Resources/Localizable.xcstrings
  python3 scripts/gen_codes.py --check    # exit 1 when either output is stale (CI, check_strings.py)

Managed string keys (source of truth = codes.v1.json; edits in Xcode are overwritten):
  code.<CODE>.title | code.<CODE>.body | code.<CODE>.action
  code.<CODE>.<data_key>.<enum_value>      (enum_strings, e.g. the reason of E_RESTORE_NOT_STARTED)
  action.<id>
  area.<token>                             (x-area-tokens: postcheck areas[].area, the words of S21 {Bereiche})
All other keys of Localizable.xcstrings belong to the app and are left untouched.
Placeholders stay literal "{name}" tokens in both languages; the app substitutes them ({App} = product name,
{x_gb} = data key x_bytes formatted as GB).
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CODES = REPO / "core" / "schema" / "codes.v1.json"
EVENTS = REPO / "core" / "schema" / "events.v1.json"
SWIFT_OUT = REPO / "app" / "Sources" / "Engine" / "Codes.generated.swift"
XCSTRINGS = REPO / "app" / "Resources" / "Localizable.xcstrings"
MANAGED_PREFIXES = ("code.", "action.", "area.")


def swift_ident(s: str) -> str:
    parts = s.replace("-", "_").split("_")
    out = parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])
    return f"`{out}`" if out in {"none", "default", "continue", "repeat", "import", "extension", "protocol",
                                  "internal", "public", "private", "static", "where", "in", "is", "as"} else out


def swift_enum(name: str, cases: list[str], doc: str, extra: str = "") -> str:
    lines = [f"/// {doc}", f"public enum {name}: String, CaseIterable, Codable, Sendable {{"]
    for c in cases:
        ident = swift_ident(c)
        lines.append(f"    case {ident}" + (f' = "{c}"' if ident.strip("`") != c else ""))
    if extra:
        lines.append(extra)
    lines.append("}")
    return "\n".join(lines)


def gen_swift(cat: dict, events: dict) -> str:
    codes = cat["codes"]
    names = sorted(codes)
    o: list[str] = [
        "// GENERATED by scripts/gen_codes.py from core/schema/codes.v1.json and events.v1.json -- do not edit.",
        "// SPDX-License-Identifier: AGPL-3.0-or-later",
        "// swiftlint:disable all",
        "import Foundation",
        "",
        f"public let engineProtocolVersion = {cat['protocol']}",
        "",
        "public enum CodeKind: String, Codable, Sendable { case error, warning, note, result }",
        "public enum DeviceModifiedDefault: String, Codable, Sendable { case no, yes, unknown, dynamic }",
        "",
        swift_enum("CodeAction", sorted(cat["actions"]), "App actions offered for a code (labels: action.<id>)."),
        "",
        "/// Every engine code of protocol v1. Unknown codes from a newer engine map to F-INTERNAL (DESIGN §5.7).",
        "public enum EngineCode: String, CaseIterable, Codable, Sendable {",
    ]
    o += [f"    case {c}" for c in names]
    o += ["", "    public struct Info: Sendable {",
          "        public let kind: CodeKind",
          "        public let screen: String",
          "        public let exitCode: Int32",
          "        public let deviceModified: DeviceModifiedDefault",
          "        public let retryable: Bool",
          "        public let needsNewBackup: Bool",
          "        public let actions: [CodeAction]",
          "        public let dataKeys: [String]",
          "    }", "",
          "    public var info: Info {",
          "        switch self {"]
    for c in names:
        e = codes[c]
        acts = ", ".join("." + swift_ident(a) for a in e["actions"])
        keys = ", ".join(json.dumps(k) for k in e["data"])
        o.append(f"        case .{c}: return Info(kind: .{e['kind']}, screen: {json.dumps(e['screen'])}, "
                 f"exitCode: {e['exit']}, deviceModified: .{e['device_modified']}, retryable: "
                 f"{str(e['retryable']).lower()}, needsNewBackup: {str(e['needs_new_backup']).lower()}, "
                 f"actions: [{acts}], dataKeys: [{keys}])")
    o += ["        }", "    }", "",
          '    public var titleKey: String { "code.\\(rawValue).title" }',
          '    public var bodyKey: String { "code.\\(rawValue).body" }',
          '    public var actionKey: String { "code.\\(rawValue).action" }',
          "}", ""]
    o.append(swift_enum("EngineCommand", events["x-commands"], "tmcore commands (DESIGN §5.4)."))
    o.append("")
    o.append(swift_enum("EnginePhase", events["$defs"]["phase"]["enum"], "Phase names; per command see phasesByCommand."))
    o.append("")
    o.append("public let phasesByCommand: [EngineCommand: [EnginePhase]] = [")
    for cmd, phases in events["x-phases"].items():
        ph = ", ".join("." + swift_ident(p) for p in phases)
        o.append(f"    .{swift_ident(cmd)}: [{ph}],")
    o.append("]")
    o.append("")
    o.append(swift_enum("CheckID", events["$defs"]["check"]["properties"]["id"]["enum"], "Check ids of 'check' events."))
    o.append("")
    o.append(swift_enum("Verdict", events["$defs"]["result_ok_postcheck"]["properties"]["verdict"]["enum"],
                        "Postcheck verdicts in priority order (DESIGN §7)."))
    o.append("")
    o.append(swift_enum("EventType", events["$defs"]["envelope"]["properties"]["type"]["enum"], "Event types."))
    o.append("")
    o.append(swift_enum("PromptKind", events["$defs"]["prompt"]["properties"]["kind"]["enum"], "Prompt overlays."))
    o.append("")
    o.append(swift_enum("DeviceState", events["$defs"]["device"]["properties"]["state"]["enum"], "device-watch states."))
    o.append("")
    return "\n".join(o)


def managed_strings(cat: dict) -> dict[str, dict[str, str]]:
    out: dict[str, dict[str, str]] = {}
    for code, e in cat["codes"].items():
        for part, tr in e["strings"].items():
            out[f"code.{code}.{part}"] = {"de": tr["de"], "en": tr["en"]}
        for key, values in e.get("enum_strings", {}).items():
            for val, tr in values.items():
                out[f"code.{code}.{key}.{val}"] = {"de": tr["de"], "en": tr["en"]}
    for aid, tr in cat["actions"].items():
        out[f"action.{aid}"] = {"de": tr["de"], "en": tr["en"]}
    for token, tr in cat.get("x-area-tokens", {}).items():
        out[f"area.{token}"] = {"de": tr["de"], "en": tr["en"]}
    return out


def merged_xcstrings(cat: dict) -> dict:
    doc = json.loads(XCSTRINGS.read_text(encoding="utf-8")) if XCSTRINGS.exists() else {}
    doc.setdefault("sourceLanguage", "de")
    doc.setdefault("version", "1.0")
    strings = doc.setdefault("strings", {})
    managed = managed_strings(cat)
    for k in [k for k in strings if k.startswith(MANAGED_PREFIXES) and k not in managed]:
        del strings[k]
    for k, tr in managed.items():
        strings[k] = {"comment": "managed by scripts/gen_codes.py (core/schema/codes.v1.json)",
                      "extractionState": "manual",
                      "localizations": {lang: {"stringUnit": {"state": "translated", "value": tr[lang]}}
                                        for lang in ("de", "en")}}
    doc["strings"] = dict(sorted(strings.items()))
    return doc


def dump_xcstrings(doc: dict) -> str:
    # Xcode writes " : " separators and 2-space indent; keep that so diffs stay small
    return json.dumps(doc, indent=2, ensure_ascii=False, separators=(",", " : ")) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="only verify that the outputs are up to date")
    a = ap.parse_args()
    cat = json.loads(CODES.read_text(encoding="utf-8"))
    events = json.loads(EVENTS.read_text(encoding="utf-8"))
    swift = gen_swift(cat, events)
    xc = dump_xcstrings(merged_xcstrings(cat))
    if a.check:
        stale = []
        if not SWIFT_OUT.exists() or SWIFT_OUT.read_text(encoding="utf-8") != swift:
            stale.append(str(SWIFT_OUT.relative_to(REPO)))
        if not XCSTRINGS.exists() or XCSTRINGS.read_text(encoding="utf-8") != xc:
            stale.append(str(XCSTRINGS.relative_to(REPO)))
        for s in stale:
            print(f"gen_codes: stale {s} (run scripts/gen_codes.py)", file=sys.stderr)
        return 1 if stale else 0
    SWIFT_OUT.parent.mkdir(parents=True, exist_ok=True)
    SWIFT_OUT.write_text(swift, encoding="utf-8")
    XCSTRINGS.parent.mkdir(parents=True, exist_ok=True)
    XCSTRINGS.write_text(xc, encoding="utf-8")
    print(f"gen_codes: {len(cat['codes'])} codes -> {SWIFT_OUT.relative_to(REPO)}, "
          f"{len(managed_strings(cat))} managed keys -> {XCSTRINGS.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
