// SPDX-License-Identifier: AGPL-3.0-or-later
// safe_seed.swift - builds a store with the SHAPE a real Threema iOS 7.4 "Threema Safe" restore produces
// (review appsafety M2 / fidelity F3: the old "(b) Safe-like" store was made by the importer itself).
//
//   safe_seed <momd> <empty-store-dir> <out-dir> <spec.json>
//
// spec (generated by make_safe_spec.py from normalized.sqlite, i.e. from the same Android data the Android Safe
// export is built from - ThreemaSafeServiceImpl.java getContacts()/getGroups()):
//   {"own": ID,
//    "contacts": [{"identity","publicKey"(hex),"verification","firstName","lastName","nickname","hidden",
//                  "createdAtMs"|null,"lastUpdateMs"|null,"private","featureMask","workVerified"}],
//    "groups":   [{"groupId"(hex),"creator"(ID, own ID for own groups),"name","lastUpdateMs"|null,"private",
//                  "members":[IDs incl. own ID when still a member]}],
//    "postRestore": [{"chat":"contact:<ID>"|"group:<hex>:<creator>","id"(hex),"text","dateMs","isOwn","read",
//                     "sender":ID|null}]}      // messages that arrived on the iPhone AFTER the Safe restore
//
// Mirrors, line by line where it matters:
//  * contacts: SafeStore.swift:743-827 (getOrCreateContact, verification, first/last/nickname, createdAt or nil,
//    hidden, readReceipt/typingIndicator default, workContact, featureMask/state from the directory fetch).
//    NO profile pictures (the Safe JSON carries none).
//  * 1:1 conversations: created only when the backup contact has lastUpdate or is private
//    (SafeStore.swift:830-850, conversation(forContact:createIfNotExisting:setLastUpdate:false)) -> lastUpdate from
//    the backup, category .private if private, NO messages, NO lastMessage.
//  * groups where I am a member: GroupManager.createOrUpdateDB (GroupManager.swift:225-370): GroupEntity state
//    active, groupCreator = creator (nil for own groups), lastPeriodicSync = now, conversation groupID/contact=creator/
//    groupMyIdentity, members = members + creator - me; then SafeStore.swift:887-897 sets groupName, category,
//    lastUpdate. Own group with only me -> startNoteGroupInfo system message (GroupManager.swift:350-356).
//  * groups where I am NOT a member ("dissolved", SafeStore.swift:904-940): GroupEntity state left, groupCreator
//    nil for own, conversation with lastUpdate (now if the backup has none), members = backup members that exist.
// The store is left in WAL mode with a non-empty -wal (like a live iPhone store).
import CoreData
import Foundation

final class Stub: ValueTransformer {
    override class func transformedValueClass() -> AnyClass { NSData.self }
    override class func allowsReverseTransformation() -> Bool { true }
    override func transformedValue(_ value: Any?) -> Any? { value }
    override func reverseTransformedValue(_ value: Any?) -> Any? { value }
}
ValueTransformer.setValueTransformer(Stub(), forName: NSValueTransformerName("GroupDeliveryReceiptValueTransformer"))

extension Data {
    init(hex: String) {
        var d = Data(); var it = hex.makeIterator()
        while let a = it.next(), let b = it.next() { d.append(UInt8(String([a, b]), radix: 16)!) }
        self = d
    }
}
func date(_ v: Any?) -> Date? { (v as? NSNumber).map { Date(timeIntervalSince1970: $0.doubleValue / 1000) } }

/// ContactEntity.updateSortInitial, default sortOrderFirstName = NO (last name first)
func sortInitial(_ identity: String, _ first: String?, _ last: String?, _ nick: String?) -> (String, Int32) {
    if identity.hasPrefix("*") { return ("*", 27) }
    var s = identity
    let f = first ?? "", l = last ?? ""
    if !f.isEmpty || !l.isEmpty { s = !l.isEmpty ? l : f } else if let nick, !nick.isEmpty { s = nick }
    if let ch = s.uppercased().first, let a = ch.asciiValue, a >= 65, a <= 90 { return (String(ch), Int32(a) - 65) }
    return ("#", 26)
}

let a = CommandLine.arguments
guard a.count == 5, let model = NSManagedObjectModel(contentsOf: URL(fileURLWithPath: a[1])) else {
    fatalError("usage: safe_seed <momd> <empty-store-dir> <out-dir> <spec.json>")
}
let out = URL(fileURLWithPath: a[3], isDirectory: true)
try? FileManager.default.removeItem(at: out)
try FileManager.default.createDirectory(at: out, withIntermediateDirectories: true)
try FileManager.default.copyItem(at: URL(fileURLWithPath: a[2]).appendingPathComponent("ThreemaData.sqlite"),
                                  to: out.appendingPathComponent("ThreemaData.sqlite"))
let spec = try JSONSerialization.jsonObject(with: Data(contentsOf: URL(fileURLWithPath: a[4]))) as! [String: Any]
let own = spec["own"] as! String
let psc = NSPersistentStoreCoordinator(managedObjectModel: model)
let store = try psc.addPersistentStore(ofType: NSSQLiteStoreType, configurationName: nil,
                                       at: out.appendingPathComponent("ThreemaData.sqlite"), options: nil)
let ctx = NSManagedObjectContext(concurrencyType: .privateQueueConcurrencyType)
ctx.persistentStoreCoordinator = psc
var counts: [String: Int] = [:]
func inc(_ k: String) { counts[k, default: 0] += 1 }
let now = Date()

ctx.performAndWait {
    func new(_ e: String) -> NSManagedObject { NSEntityDescription.insertNewObject(forEntityName: e, into: ctx) }
    var contacts: [String: NSManagedObject] = [:]
    var oneToOne: [String: NSManagedObject] = [:]
    var groupConvs: [String: NSManagedObject] = [:]
    for c in spec["contacts"] as! [[String: Any]] {
        let id = c["identity"] as! String
        guard id != own else { continue }                                     // SafeStore.swift:710-713
        let o = new("Contact")
        o.setValue(id, forKey: "identity")
        o.setValue(Data(hex: c["publicKey"] as! String), forKey: "publicKey")
        o.setValue(NSNumber(value: Int16((c["verification"] as? Int) ?? 0)), forKey: "verificationLevel")
        let first = c["firstName"] as? String, last = c["lastName"] as? String, nick = c["nickname"] as? String
        o.setValue(first, forKey: "firstName")
        o.setValue(last, forKey: "lastName")
        o.setValue(nick, forKey: "publicNickname")
        let (si, idx) = sortInitial(id, first, last, nick)
        o.setValue(si, forKey: "sortInitial")
        o.setValue(NSNumber(value: idx), forKey: "sortIndex")
        o.setValue(date(c["createdAtMs"]), forKey: "createdAt")             // nil when the backup has 0/none
        o.setValue(NSNumber(value: Int16((c["hidden"] as? Bool ?? false) ? 1 : 0)), forKey: "hidden")
        o.setValue(NSNumber(value: Int16(0)), forKey: "readReceipts")          // .default
        o.setValue(NSNumber(value: Int16(0)), forKey: "typingIndicators")      // .default
        o.setValue(NSNumber(value: Int16((c["workVerified"] as? Bool ?? false) ? 1 : 0)), forKey: "workContact")
        o.setValue(NSNumber(value: Int64((c["featureMask"] as? Int) ?? 255)), forKey: "featureMask")
        o.setValue(NSNumber(value: Int16(0)), forKey: "state")                 // directory: active
        o.setValue(NSNumber(value: Int16(0)), forKey: "forwardSecurityState")
        contacts[id] = o
        inc("contacts")
        if c["hidden"] as? Bool ?? false { inc("contacts_hidden") }
        // 1:1 conversation only with lastUpdate or private (SafeStore.swift:830-850)
        let isPrivate = c["private"] as? Bool ?? false
        if c["lastUpdateMs"] is NSNumber || isPrivate {
            let conv = new("Conversation")
            conv.setValue(o, forKey: "contact")
            conv.setValue(date(c["lastUpdateMs"]), forKey: "lastUpdate")
            conv.setValue(NSNumber(value: Int16(isPrivate ? 1 : 0)), forKey: "category")
            conv.setValue(NSNumber(value: Int16(0)), forKey: "visibility")
            conv.setValue(NSNumber(value: Int32(0)), forKey: "unreadMessageCount")
            conv.setValue(NSNumber(value: false), forKey: "marked")
            oneToOne[id] = conv
            inc("conversations_1to1_empty")
            if isPrivate { inc("conversations_private") }
        }
    }
    for g in spec["groups"] as! [[String: Any]] {
        let gid = Data(hex: g["groupId"] as! String)
        let creator = g["creator"] as! String
        let members = (g["members"] as? [String] ?? []).map { $0.uppercased() }
        let isOwnGroup = creator == own
        let isPrivate = g["private"] as? Bool ?? false
        let ge = new("Group")
        ge.setValue(gid, forKey: "groupId")
        let conv = new("Conversation")
        conv.setValue(gid, forKey: "groupId")
        conv.setValue(own, forKey: "groupMyIdentity")
        conv.setValue(isOwnGroup ? nil : contacts[creator], forKey: "contact")
        conv.setValue(g["name"] as? String, forKey: "groupName")
        conv.setValue(NSNumber(value: Int16(isPrivate ? 1 : 0)), forKey: "category")
        conv.setValue(NSNumber(value: Int16(0)), forKey: "visibility")
        conv.setValue(NSNumber(value: Int32(0)), forKey: "unreadMessageCount")
        conv.setValue(NSNumber(value: false), forKey: "marked")
        conv.setValue(date(g["lastUpdateMs"]) ?? now, forKey: "lastUpdate")  // conversationEntity() sets .now first
        let mset = conv.mutableSetValue(forKey: "members")
        if members.contains(own) {
            // createOrUpdateDB: creator contact must exist for foreign groups (GroupManager.swift:215-218)
            if !isOwnGroup && contacts[creator] == nil { ctx.delete(ge); ctx.delete(conv); inc("groups_skipped_creator_missing"); continue }
            ge.setValue(NSNumber(value: Int16(0)), forKey: "state")                    // active
            ge.setValue(isOwnGroup ? nil : creator, forKey: "groupCreator")
            ge.setValue(now, forKey: "lastPeriodicSync")
            var all = Set(members); all.insert(creator)
            for m in all.sorted() where m != own {
                if let c = contacts[m] { mset.add(c) } else { inc("group_member_contact_missing") }
            }
            if isOwnGroup && all == [own] {
                let sm = new("SystemMessage")                                       // GroupManager.swift:350-356
                sm.setValue(NSNumber(value: Int16(17)), forKey: "type")            // startNoteGroupInfo
                sm.setValue(Data((0..<8).map { _ in UInt8.random(in: 0...255) }), forKey: "id")
                sm.setValue(now, forKey: "date"); sm.setValue(now, forKey: "remoteSentDate")
                sm.setValue(true, forKey: "isOwn"); sm.setValue(true, forKey: "sent"); sm.setValue(true, forKey: "read")
                sm.setValue(true, forKey: "delivered"); sm.setValue(false, forKey: "userack")
                sm.setValue(conv, forKey: "conversation")
                conv.setValue(sm, forKey: "lastMessage")   // EntityCreator.systemMessageEntity: isAllowedAsLastMessage
                inc("note_group_system_messages")
            }
            inc("groups_active")
        } else {
            ge.setValue(NSNumber(value: Int16(2)), forKey: "state")                    // left ("dissolved")
            ge.setValue(isOwnGroup ? nil : creator, forKey: "groupCreator")
            for m in members { if let c = contacts[m] { mset.add(c) } }
            inc("groups_left")
        }
        groupConvs["\(gid.map { String(format: "%02x", $0) }.joined()):\(creator)"] = conv
    }
    for m in spec["postRestore"] as? [[String: Any]] ?? [] {
        let chat = m["chat"] as! String
        let conv: NSManagedObject?
        if chat.hasPrefix("contact:") {
            let id = String(chat.dropFirst(8))
            conv = oneToOne[id] ?? {
                guard let c = contacts[id] else { return nil }
                let cv = new("Conversation"); cv.setValue(c, forKey: "contact")
                cv.setValue(NSNumber(value: Int16(0)), forKey: "category"); cv.setValue(NSNumber(value: Int16(0)), forKey: "visibility")
                oneToOne[id] = cv; return cv
            }()
        } else { conv = groupConvs[String(chat.dropFirst(6))] }
        guard let conv else { inc("post_restore_chat_missing"); continue }
        let msg = new("TextMessage")
        let d = date(m["dateMs"])!
        let isOwn = m["isOwn"] as? Bool ?? false
        msg.setValue(Data(hex: m["id"] as! String), forKey: "id")
        msg.setValue(m["text"], forKey: "text")
        msg.setValue(d, forKey: "date"); msg.setValue(d, forKey: "remoteSentDate")
        msg.setValue(isOwn, forKey: "isOwn"); msg.setValue(true, forKey: "sent"); msg.setValue(true, forKey: "delivered")
        msg.setValue(isOwn || (m["read"] as? Bool ?? false), forKey: "read"); msg.setValue(false, forKey: "userack")
        if let s = m["sender"] as? String, let c = contacts[s] { msg.setValue(c, forKey: "sender") }
        msg.setValue(conv, forKey: "conversation")
        if (conv.value(forKey: "lastUpdate") as? Date ?? .distantPast) <= d { conv.setValue(d, forKey: "lastUpdate") }
        let lm = conv.value(forKey: "lastMessage") as? NSManagedObject
        if (lm?.value(forKey: "date") as? Date ?? .distantPast) <= d { conv.setValue(msg, forKey: "lastMessage") }
        if !isOwn && !(m["read"] as? Bool ?? false) {
            conv.setValue(NSNumber(value: ((conv.value(forKey: "unreadMessageCount") as? NSNumber)?.int32Value ?? 0) + 1),
                          forKey: "unreadMessageCount")
        }
        inc("post_restore_messages")
    }
    try! ctx.save()
}
_ = store
// no psc.remove -> the WAL stays (process exits without checkpointing, like a live iPhone store)
let wal = out.appendingPathComponent("ThreemaData.sqlite-wal").path
let size = (try? FileManager.default.attributesOfItem(atPath: wal)[.size] as? Int) ?? 0
let cj = (try? JSONSerialization.data(withJSONObject: counts, options: [.sortedKeys])).flatMap { String(data: $0, encoding: .utf8) } ?? "{}"
print("safe-seeded \(out.path) wal_bytes=\(size) counts=\(cj)")
exit(0)
